# Generated by Django 5.2 on 2025-05-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='sitemap_agent_type',
            field=models.CharField(choices=[('agno', 'Agno Agent'), ('qwen', 'Qwen Agent')], default='agno', help_text='Type of agent to use for sitemap generation', max_length=20),
        ),
    ]
