# Generated by Django 5.2 on 2025-05-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0002_datasource_sitemap_agent_type'),
    ]

    operations = [
    ]
