# Generated by Django 5.2 on 2025-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0003_add_enable_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='enable_fallback',
            field=models.BooleanField(default=True, help_text='Enable fallback to URL-based hierarchy when LLM fails'),
        ),
    ]
