# Generated by Django 5.2 on 2025-05-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0004_datasource_enable_fallback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='enable_fallback',
        ),
    ]
